#Requires -Version 5.1
<#
.SYNOPSIS
  Interactive wizard — creates platform/deploy/deploy.config (not committed to git).

.USAGE
  powershell -ExecutionPolicy Bypass -File deploy\configure.ps1
#>
param(
  [switch]$Force
)

$ErrorActionPreference = "Stop"
$DeployDir = $PSScriptRoot
$OutFile = Join-Path $DeployDir "deploy.config"

function Prompt-Value {
  param(
    [string]$Label,
    [string]$Default = ""
  )
  if ($Default) {
    $input = Read-Host "$Label [$Default]"
    if ([string]::IsNullOrWhiteSpace($input)) { return $Default }
    return $input.Trim()
  }
  return (Read-Host $Label).Trim()
}

function Prompt-YesNo {
  param(
    [string]$Label,
    [bool]$Default = $false
  )
  $hint = if ($Default) { "Y/n" } else { "y/N" }
  $input = (Read-Host "$Label ($hint)").Trim().ToLowerInvariant()
  if (-not $input) { return $Default }
  return $input -in @("y", "yes", "1", "да", "d")
}

function Try-GhToken {
  if (-not (Get-Command gh -ErrorAction SilentlyContinue)) { return "" }
  try {
    $t = gh auth token 2>$null
    if ($LASTEXITCODE -eq 0 -and $t) { return $t.Trim() }
  } catch {}
  return ""
}

function Try-GitHubRepo {
  $root = Split-Path $DeployDir -Parent | Split-Path -Parent
  if (-not (Test-Path (Join-Path $root ".git"))) { return "" }
  Push-Location $root
  try {
    $url = git remote get-url origin 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $url) { return "" }
    if ($url -match "github\.com[:/](.+?)(?:\.git)?$") {
      return "https://github.com/$($Matches[1]).git"
    }
  } finally {
    Pop-Location
  }
  return ""
}

Write-Host ""
Write-Host "=== MinerPulse deploy.config wizard ===" -ForegroundColor Cyan
Write-Host "Values are saved to: $OutFile" -ForegroundColor DarkGray
Write-Host "(file is in .gitignore — secrets stay local)" -ForegroundColor DarkGray
Write-Host ""

if ((Test-Path $OutFile) -and -not $Force) {
  if (-not (Prompt-YesNo "deploy.config already exists. Overwrite?" $false)) {
    Write-Host "Cancelled." -ForegroundColor Yellow
    exit 0
  }
}

$defaultRepo = Try-GitHubRepo
if (-not $defaultRepo) { $defaultRepo = "https://github.com/BobJustFry/MinerPulse.git" }

Write-Host "--- GitHub ---" -ForegroundColor Yellow
$githubRepo = Prompt-Value "GitHub repo URL" $defaultRepo
$githubBranch = Prompt-Value "Branch" "main"

$ghToken = Try-GhToken
if ($ghToken) {
  Write-Host "GitHub token: found via 'gh auth token'" -ForegroundColor Green
  if (-not (Prompt-YesNo "Use this token for private repo clone on VPS?" $true)) {
    $ghToken = Prompt-Value "GitHub token (empty = public repo only)" ""
  }
} else {
  Write-Host "GitHub CLI not logged in — leave token empty if repo is public." -ForegroundColor DarkGray
  $ghToken = Prompt-Value "GitHub token (repo scope, optional)" ""
}

Write-Host ""
Write-Host "--- VPS ---" -ForegroundColor Yellow
$vpsHost = Prompt-Value "VPS IP or hostname" "82.23.249.197"
$vpsUser = Prompt-Value "SSH user" "root"
$sshKey = Prompt-Value "SSH private key path (empty = default)" ""
$remoteDir = Prompt-Value "Repo path on VPS" "/opt/minerpulse"
$platformSubdir = Prompt-Value "Platform subfolder in repo" "platform"

Write-Host ""
Write-Host "--- Site ---" -ForegroundColor Yellow
$baseDomain = Prompt-Value "Base domain" "mpulse.bob4.fun"
$letsencryptEmail = Prompt-Value "Let's Encrypt email" "admin@bob4.fun"
Write-Host "Deploy mode: standalone (80/443) | external-proxy (SharedAI) | custom-ports (8443)"
$deployMode = Prompt-Value "Deploy mode" "external-proxy"
$adminUsername = Prompt-Value "Super admin username" "mpulse-admin"

Write-Host ""
Write-Host "--- SharedAI / reverse proxy ---" -ForegroundColor Yellow
$integrateProxy = Prompt-YesNo "Auto-add mpulse blocks to existing Caddy on VPS?" $true
$sharedAiDir = "/opt/sharedai"
if ($integrateProxy) {
  $sharedAiDir = Prompt-Value "SharedAI directory on VPS" "/opt/sharedai"
}

$autoIntegrate = if ($integrateProxy) { "1" } else { "0" }

$content = @"
# Generated by deploy/configure.ps1 — do not commit

GITHUB_REPO=$githubRepo
GITHUB_BRANCH=$githubBranch
GITHUB_TOKEN=$ghToken

VPS_HOST=$vpsHost
VPS_USER=$vpsUser
SSH_KEY=$sshKey
REMOTE_DIR=$remoteDir
PLATFORM_SUBDIR=$platformSubdir

MPULSE_BASE_DOMAIN=$baseDomain
MPULSE_LETSENCRYPT_EMAIL=$letsencryptEmail
MPULSE_DEPLOY_MODE=$deployMode
MPULSE_ADMIN_IP_ALLOWLIST=
MPULSE_LICENSE_OFFLINE_GRACE_DAYS=14

MPULSE_BOOTSTRAP_ADMIN_USERNAME=$adminUsername
MPULSE_BOOTSTRAP_ADMIN_PASSWORD=
MPULSE_POSTGRES_PASSWORD=

SHARED_AI_DIR=$sharedAiDir
SHARED_AI_CADDYFILE=
SHARED_AI_COMPOSE_FILE=
SHARED_AI_CADDY_SERVICE=caddy
AUTO_INTEGRATE_PROXY=$autoIntegrate
"@

Set-Content -Path $OutFile -Value $content -Encoding UTF8 -NoNewline
Add-Content -Path $OutFile -Value "`n"

Write-Host ""
Write-Host "=== Saved ===" -ForegroundColor Green
Write-Host "  $OutFile"
Write-Host ""
Write-Host "Super admin password will be generated on the server during install."
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  powershell -ExecutionPolicy Bypass -File deploy\setup-from-github.ps1"
Write-Host ""
Write-Host "Or on VPS (after git pull):" -ForegroundColor Cyan
Write-Host "  sudo bash $remoteDir/$platformSubdir/deploy/bootstrap-from-github.sh $remoteDir/$platformSubdir/deploy/deploy.config install"
