#!/usr/bin/env bash
# Interactive wizard — creates deploy/deploy.config (gitignored).
#
#   bash deploy/configure.sh
#   bash deploy/configure.sh --force

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${ROOT}/deploy.config"
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

prompt() {
  local label="$1"
  local default="${2:-}"
  local input
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " input
    printf '%s' "${input:-$default}"
  else
    read -r -p "$label: " input
    printf '%s' "$input"
  fi
}

prompt_secret() {
  local label="$1"
  local input
  read -r -s -p "$label: " input
  echo
  printf '%s' "$input"
}

prompt_yn() {
  local label="$1"
  local default="${2:-n}"
  local hint reply
  if [[ "$default" == "y" ]]; then hint="Y/n"; else hint="y/N"; fi
  read -r -p "$label ($hint): " reply
  reply="${reply:-$default}"
  [[ "$reply" =~ ^[Yy1Дд]$ ]]
}

try_gh_token() {
  command -v gh >/dev/null 2>&1 || return 0
  gh auth token 2>/dev/null || true
}

try_git_repo() {
  local repo_root
  repo_root="$(cd "$ROOT/../.." && pwd)"
  if [[ ! -d "$repo_root/.git" ]]; then
    echo "https://github.com/BobJustFry/MinerPulse.git"
    return
  fi
  local url
  url="$(git -C "$repo_root" remote get-url origin 2>/dev/null || true)"
  if [[ "$url" =~ github.com[:/](.+)(\.git)?$ ]]; then
    echo "https://github.com/${BASH_REMATCH[1]%.git}.git"
  else
    echo "https://github.com/BobJustFry/MinerPulse.git"
  fi
}

echo ""
echo "=== MinerPulse deploy.config wizard ==="
echo "Output: $OUT (not committed to git)"
echo ""

if [[ -f "$OUT" && "$FORCE" -ne 1 ]]; then
  if ! prompt_yn "deploy.config already exists. Overwrite?" n; then
    echo "Cancelled."
    exit 0
  fi
fi

DEFAULT_REPO="$(try_git_repo)"

echo "--- GitHub ---"
GITHUB_REPO="$(prompt "GitHub repo URL" "$DEFAULT_REPO")"
GITHUB_BRANCH="$(prompt "Branch" "main")"

GH_TOKEN="$(try_gh_token)"
if [[ -n "$GH_TOKEN" ]]; then
  echo "GitHub token: found via 'gh auth token'"
  if prompt_yn "Use this token for VPS clone?" y; then
    GITHUB_TOKEN="$GH_TOKEN"
  else
    GITHUB_TOKEN="$(prompt_secret "GitHub token (optional)")"
  fi
else
  GITHUB_TOKEN="$(prompt "GitHub token (optional, public repo = empty)" "")"
fi

echo ""
echo "--- VPS ---"
VPS_HOST="$(prompt "VPS IP or hostname" "82.23.249.197")"
VPS_USER="$(prompt "SSH user" "root")"
SSH_KEY="$(prompt "SSH private key path (optional)" "")"
REMOTE_DIR="$(prompt "Repo path on VPS" "/opt/minerpulse")"
PLATFORM_SUBDIR="$(prompt "Platform subfolder" "platform")"

echo ""
echo "--- Site ---"
MPULSE_BASE_DOMAIN="$(prompt "Base domain" "mpulse.bob4.fun")"
MPULSE_LETSENCRYPT_EMAIL="$(prompt "Let's Encrypt email" "admin@bob4.fun")"
echo "Deploy mode: standalone | external-proxy | custom-ports"
MPULSE_DEPLOY_MODE="$(prompt "Deploy mode" "external-proxy")"
MPULSE_BOOTSTRAP_ADMIN_USERNAME="$(prompt "Super admin username" "mpulse-admin")"

echo ""
echo "--- SharedAI ---"
if prompt_yn "Auto-add mpulse to existing Caddy?" y; then
  AUTO_INTEGRATE_PROXY=1
  SHARED_AI_DIR="$(prompt "SharedAI directory" "/opt/sharedai")"
  SHARED_AI_CADDYFILE="$(prompt "Caddyfile path on VPS" "/opt/sharedai/infra/caddy/Caddyfile")"
else
  AUTO_INTEGRATE_PROXY=0
  SHARED_AI_DIR="/opt/sharedai"
  SHARED_AI_CADDYFILE=""
fi

cat >"$OUT" <<EOF
# Generated by deploy/configure.sh — do not commit

GITHUB_REPO=${GITHUB_REPO}
GITHUB_BRANCH=${GITHUB_BRANCH}
GITHUB_TOKEN=${GITHUB_TOKEN}

VPS_HOST=${VPS_HOST}
VPS_USER=${VPS_USER}
SSH_KEY=${SSH_KEY}
REMOTE_DIR=${REMOTE_DIR}
PLATFORM_SUBDIR=${PLATFORM_SUBDIR}

MPULSE_BASE_DOMAIN=${MPULSE_BASE_DOMAIN}
MPULSE_LETSENCRYPT_EMAIL=${MPULSE_LETSENCRYPT_EMAIL}
MPULSE_DEPLOY_MODE=${MPULSE_DEPLOY_MODE}
MPULSE_ADMIN_IP_ALLOWLIST=
MPULSE_LICENSE_OFFLINE_GRACE_DAYS=14

MPULSE_BOOTSTRAP_ADMIN_USERNAME=${MPULSE_BOOTSTRAP_ADMIN_USERNAME}
MPULSE_BOOTSTRAP_ADMIN_PASSWORD=
MPULSE_POSTGRES_PASSWORD=

SHARED_AI_DIR=${SHARED_AI_DIR}
SHARED_AI_CADDYFILE=${SHARED_AI_CADDYFILE}
SHARED_AI_COMPOSE_FILE=
SHARED_AI_CADDY_SERVICE=caddy
AUTO_INTEGRATE_PROXY=${AUTO_INTEGRATE_PROXY}
MPULSE_HOST_UPSTREAM=
MPULSE_DNS_WAIT_SECONDS=120
EOF

chmod 600 "$OUT"

echo ""
echo "=== Saved: $OUT ==="
echo "Super admin password will be generated during install."
echo ""
echo "Next on VPS:"
echo "  sudo bash ${REMOTE_DIR}/${PLATFORM_SUBDIR}/deploy/bootstrap-from-github.sh ${OUT} install"
