#!/usr/bin/env bash
# Map deploy.config variables to install.sh environment.

export_install_env() {
  export MPULSE_NONINTERACTIVE=1
  export MPULSE_BASE_DOMAIN="${MPULSE_BASE_DOMAIN:-mpulse.bob4.fun}"
  export MPULSE_LETSENCRYPT_EMAIL="${MPULSE_LETSENCRYPT_EMAIL:-admin@bob4.fun}"
  export MPULSE_DEPLOY_MODE="${MPULSE_DEPLOY_MODE:-external-proxy}"
  export MPULSE_HTTP_PORT="${MPULSE_HTTP_PORT:-80}"
  export MPULSE_HTTPS_PORT="${MPULSE_HTTPS_PORT:-443}"
  export MPULSE_ADMIN_IP_ALLOWLIST="${MPULSE_ADMIN_IP_ALLOWLIST:-}"
  export MPULSE_LICENSE_OFFLINE_GRACE_DAYS="${MPULSE_LICENSE_OFFLINE_GRACE_DAYS:-14}"
  export MPULSE_BOOTSTRAP_ADMIN_EMAIL="${MPULSE_BOOTSTRAP_ADMIN_EMAIL:?MPULSE_BOOTSTRAP_ADMIN_EMAIL required}"
  export MPULSE_BOOTSTRAP_ADMIN_PASSWORD="${MPULSE_BOOTSTRAP_ADMIN_PASSWORD:-}"
  export MPULSE_POSTGRES_PASSWORD="${MPULSE_POSTGRES_PASSWORD:-}"
}
