#!/usr/bin/env bash
# Map deploy.config variables to install.sh environment.

export_install_env() {
  export MPULSE_NONINTERACTIVE=1
  export MPULSE_BASE_DOMAIN="${MPULSE_BASE_DOMAIN:-mpulse.bob4.fun}"
  export MPULSE_LETSENCRYPT_EMAIL="${MPULSE_LETSENCRYPT_EMAIL:-admin@bob4.fun}"
  export MPULSE_DEPLOY_MODE="${MPULSE_DEPLOY_MODE:-external-proxy}"
  export MPULSE_HTTP_PORT="${MPULSE_HTTP_PORT:-80}"
  export MPULSE_HTTPS_PORT="${MPULSE_HTTPS_PORT:-443}"
  export MPULSE_ADMIN_IP_ALLOWLIST="${MPULSE_ADMIN_IP_ALLOWLIST:-}"
  export MPULSE_LICENSE_OFFLINE_GRACE_DAYS="${MPULSE_LICENSE_OFFLINE_GRACE_DAYS:-14}"
  export MPULSE_BOOTSTRAP_ADMIN_USERNAME="${MPULSE_BOOTSTRAP_ADMIN_USERNAME:-mpulse-admin}"
  export MPULSE_BOOTSTRAP_ADMIN_PASSWORD="${MPULSE_BOOTSTRAP_ADMIN_PASSWORD:-}"
  export MPULSE_POSTGRES_PASSWORD="${MPULSE_POSTGRES_PASSWORD:-}"
  export MPULSE_HOST_UPSTREAM="${MPULSE_HOST_UPSTREAM:-}"
  export MPULSE_DNS_WAIT_SECONDS="${MPULSE_DNS_WAIT_SECONDS:-120}"
  export SHARED_AI_DIR="${SHARED_AI_DIR:-/opt/sharedai}"
  export SHARED_AI_CADDYFILE="${SHARED_AI_CADDYFILE:-}"
  export SHARED_AI_COMPOSE_FILE="${SHARED_AI_COMPOSE_FILE:-}"
  export SHARED_AI_CADDY_SERVICE="${SHARED_AI_CADDY_SERVICE:-caddy}"
  export AUTO_INTEGRATE_PROXY="${AUTO_INTEGRATE_PROXY:-0}"
}
