BASE_DOMAIN={{BASE_DOMAIN}}
LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}
DEPLOY_MODE={{DEPLOY_MODE}}
HTTP_PORT={{HTTP_PORT}}
HTTPS_PORT={{HTTPS_PORT}}
ADMIN_IP_ALLOWLIST={{ADMIN_IP_ALLOWLIST}}

POSTGRES_USER=mpulse
POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
POSTGRES_DB=mpulse
DATABASE_URL=postgresql://mpulse:{{POSTGRES_PASSWORD}}@postgres:5432/mpulse

JWT_PRIVATE_KEY="{{JWT_PRIVATE_KEY}}"
JWT_PUBLIC_KEY="{{JWT_PUBLIC_KEY}}"
LICENSE_OFFLINE_GRACE_DAYS={{LICENSE_OFFLINE_GRACE_DAYS}}
BETA_SELF_SERVICE={{BETA_SELF_SERVICE}}
BETA_MAX_DEVICES={{BETA_MAX_DEVICES}}

API_PORT=3001
WEB_PORT=3000
ADMIN_PORT=3002

PUBLIC_API_URL=https://api.{{BASE_DOMAIN}}{{PUBLIC_URL_HTTPS_SUFFIX}}
PUBLIC_WEB_URL=https://{{BASE_DOMAIN}}{{PUBLIC_URL_HTTPS_SUFFIX}}
PUBLIC_ADMIN_URL=https://admin.{{BASE_DOMAIN}}{{PUBLIC_URL_HTTPS_SUFFIX}}

BOOTSTRAP_ADMIN_USERNAME={{BOOTSTRAP_ADMIN_USERNAME}}
BOOTSTRAP_ADMIN_PASSWORD={{BOOTSTRAP_ADMIN_PASSWORD}}
